from __future__ import annotations

import struct

EV_KEY = 0x01
KEY_LEFTCTRL = 29
KEY_RIGHTCTRL = 97
KEY_ESC = 1
KEY_LEFTALT = 56
KEY_RIGHTALT = 100
KEY_LEFTMETA = 125
KEY_RIGHTMETA = 126
KEY_LEFTSHIFT = 42
KEY_RIGHTSHIFT = 54
KEY_SPACE = 57
KEY_F8 = 66
KEY_F9 = 67

KEY_NAME_TO_CODES = {
    "ctrl": {KEY_LEFTCTRL, KEY_RIGHTCTRL},
    "control": {KEY_LEFTCTRL, KEY_RIGHTCTRL},
    "alt": {KEY_LEFTALT, KEY_RIGHTALT},
    "super": {KEY_LEFTMETA, KEY_RIGHTMETA},
    "meta": {KEY_LEFTMETA, KEY_RIGHTMETA},
    "shift": {KEY_LEFTSHIFT, KEY_RIGHTSHIFT},
    "space": {KEY_SPACE},
    "f8": {KEY_F8},
    "f9": {KEY_F9},
}

EVENT_STRUCT = struct.Struct("llHHI")
